### ISSUE TITLE
Source Code is not working

### ISSUE THREAD

**Issue by justintham** [Sgvkamalakar/Azure-Talking-Avatar#1]
Hi,

I have try to open the demo that provided. After I clicked the "submit job" there is nothing happen.

I have another question. Where can I get these 3 information? Is it from Azure Speech Service or Azure Communication Service?
SUBSCRIPTION_KEY=<your_subscription_key>
SERVICE_REGION=<your_service_region>
SERVICE_HOST=<your_service_host>

**Comment by Sgvkamalakar** [comment]
Hi,

The resource group I created during this project was initially free but later incurred charges. As a result, I revoked the resource group and credentials. Due to this action, the app is currently non-functional.

You can create an* Azure Speech Service* through Azure Portal, create a resource group of your choice, and get the credentials.

For more info check out the Azure Speech Studio .. https://speech.microsoft.com/

**Comment by justintham** [comment]
> Hi, The resource group I created during this project was initially free but later incurred charges. As a result, I revoked the resource group and credentials. Due to this action, the app is currently non-functional. You can create an* Azure Speech Service* through Azure Portal, create a resource group of your choice, and get the credentials. For more info check out the Azure Speech Studio .. https://speech.microsoft.com/

![image](https://github.com/Sgvkamalakar/Azure-Talking-Avatar/assets/81354747/d8bb9702-189f-4f71-89f7-94b3ee510062)

HI,

But I unable to find the "SERVICE_HOST" from the "Azure Speech Service". Is the Endpoint indicate as "SERVICE_HOST"??

**Comment by Sgvkamalakar** [comment]
You have the choice to use a preset one such as `customvoice.api.speech.microsoft.com`

```bash
https://{SERVICE_REGION}.customvoice.api.speech.microsoft.com/api/texttospeech/3.1-preview1/batchsynthesis/talkingavatar
